version: '3.8'

services:
  appdb:
    image: postgres
    container_name: appdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oy159753
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oy159753
      SPRING_DATASOURCE_URL: jdbc:postgresql://appdb:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: oy159753
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - appdb
volumes:
  app-db-data:
