version: '3.8'

services:
  appdb:
    image: postgres
    container_name: appdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oy159753
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oy159753
      SPRING_DATASOURCE_URL: jdbc:postgresql://appdb:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: oy159753
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - appdb

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"  # Nginx in the react-app service listens on port 80 internally

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"    # Nginx listens on port 80 on the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx configuration
    depends_on:
      - react-app
      - spring-boot-app

volumes:
  app-db-data:
