spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/appdb
    username: postgres
    password: oy159753
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect