on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: |
        if [ "${{ github.ref_name }}" == "master" ]; then
          mvn -B package --file backend/pom.xml
        elif [ "${{ github.ref_name }}" == "localhost" ]; then
          mvn -B package --file local_backend/pom.xml
        fi

    - name: Publish to GitHub Packages Apache Maven
      run: |
        if [ "${{ github.ref_name }}" == "master" ]; then
          mvn -X deploy -s $GITHUB_WORKSPACE/settings.xml --file backend/pom.xml \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/omeryldzk/spring-boot-atmProject
        elif [ "${{ github.ref_name }}" == "localhost" ]; then
          mvn -X deploy -s $GITHUB_WORKSPACE/settings.xml --file local_backend/pom.xml \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/omeryldzk/spring-boot-atmProject
        fi
  

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
